/**
 * @file requirements-analysis-service.ts
 * @description Orchestrates the requirements extraction pipeline.
 */

import { RequirementsAnalysis, Requirement, RequirementStatus } from './requirement-types';
import { RequirementExtractor } from './requirement-extractor'; // Mocked below
import { RequirementValidator } from './requirement-validator';
import { RequirementClassifier } from './requirement-classifier';
import { auditLogger } from '../../core/logging/audit-logger';

export class RequirementsAnalysisService {
    private validator = new RequirementValidator();
    private classifier = new RequirementClassifier();

    /**
     * Initiates the requirements extraction process.
     */
    async extractRequirements(leadId: string, researchData: any, painAnalysis: any): Promise<{ taskId: string; prompt: string }> {
        // Logic for triggering the Manual AI Bridge (similar to Phase 6)
        const prompt = `[PROMPT GENERATED BY RequirementPromptGenerator]`;
        const taskId = `req_ext_${leadId}_${Date.now()}`;

        await auditLogger.log({
            action: 'REQUIREMENTS_EXTRACTION_INITIATED',
            entityType: 'RequirementsAnalysis',
            entityId: leadId,
            details: { taskId },
        });

        return { taskId, prompt };
    }

    /**
     * Processes results from the Manual AI Bridge.
     */
    async processAnalysisResult(
        leadId: string,
        aiResponse: string,
        researchData: any,
        painAnalysis: any
    ): Promise<RequirementsAnalysis> {
        // 1. Extract Candidate Requirements (Mocked parsing)
        const candidates = this.parseAIResponse(aiResponse);

        // 2. Validation & Classification
        const validatedRequirements: Requirement[] = [];

        for (const candidate of candidates) {
            const validation = this.validator.validate(candidate, researchData.evidence);

            if (!validation.isValid) {
                console.log(`[VALIDATOR] Rejected requirement: ${validation.reason}`);
                continue; // Drop solutioning attempts
            }

            // Get source pain for priority calculation
            const sourcePain = painAnalysis.pains.find((p: any) => p.id === candidate.sourcePainId);
            const severity = sourcePain?.severity || 'UNKNOWN';
            const signal = 'MEDIUM'; // Mocked signal from Phase 5

            const { priority, type } = this.classifier.classify(candidate, severity, signal);

            validatedRequirements.push({
                ...candidate,
                priority,
                type,
                certainty: validation.updatedCertainty,
                status: 'VALIDATED',
            });
        }

        const analysis: RequirementsAnalysis = {
            id: `req_an_${Date.now()}`,
            leadId,
            researchVersionId: researchData.versionId,
            qualificationVersionId: 'q_1',
            painAnalysisVersionId: painAnalysis.id,
            analysisVersion: 1,
            status: 'DRAFT',
            overallCompleteness: 0.8,
            overallConfidence: 0.7,
            requirements: validatedRequirements,
            unresolvedQuestions: [],
            createdAt: new Date(),
        };

        await auditLogger.log({
            action: 'REQUIREMENTS_ANALYSIS_COMPLETED',
            entityType: 'RequirementsAnalysis',
            entityId: leadId,
            details: { reqCount: validatedRequirements.length },
        });

        return analysis;
    }

    private parseAIResponse(response: string): any[] {
        // Mock parsing logic
        return [{
            title: 'Automatic Lead Routing',
            description: 'The solution must automatically identify and route new qualified leads.',
            sourcePainId: 'pain_123',
            evidence: [{ evidenceId: 'e1', contributionType: 'SUPPORTING' }],
            certainty: 'INFERRED',
            confidence: 0.8,
            type: 'FUNCTIONAL',
        }];
    }
}

